###################################################
# Base Forwarder App (All Systems)
###################################################

[serverClass:all_forwarders]
whitelist.0 = *

[serverClass:all_forwarders:app:TA_base_forwarder]

###################################################
# Linux Systems
###################################################

[serverClass:linux_servers]
whitelist.0 = linux*
whitelist.1 = ubuntu*

[serverClass:linux_servers:app:TA_linux_logs]

###################################################
# Windows Systems
###################################################

[serverClass:windows_servers]
whitelist.0 = win*
whitelist.1 = windows*

[serverClass:windows_servers:app:TA_windows_logs]

###################################################
# Windows Systems with Sysmon
###################################################

[serverClass:windows_sysmon]
whitelist.0 = win*
whitelist.1 = windows*

[serverClass:windows_sysmon:app:TA_sysmon_logs]